CREATE TABLE [dbo].[CONFIGURACION]
(
	[UNIDAD_TIEMPO_PARAMETROS_REPRODUCTIVOS]	CHAR	NOT NULL,
	[DIAS_ALERTA_PALPACION]						INT		NOT NULL,
	[DIAS_ALERTA_PARTO]							INT		NOT NULL,
	[DIAS_ALERTA_IEP]							INT		NOT NULL,
	[DIAS_ALERTA_ULTIMO_IEP]					INT		NOT NULL,
	[DIAS_ALERTA_IEP_HISTORICO]					INT		NOT NULL,
	[DIAS_ALERTA_ULTIMO_IEP_HISTORICO]			INT		NOT NULL,

	CONSTRAINT CK_CHECK_CONFIGURACION CHECK (UNIDAD_TIEMPO_PARAMETROS_REPRODUCTIVOS IN ('M', 'S', 'D'))
)
