CREATE TABLE [dbo].[DESARROLLO]
(
	[PK_ID_DESARROLLO]		INT				NOT NULL	IDENTITY (1, 1),
	[ESTADO]				NVARCHAR(50)	NOT NULL,

	CONSTRAINT CK_PK_ID_DESARROLLO PRIMARY KEY CLUSTERED ([PK_ID_DESARROLLO] ASC)
)
