CREATE TABLE [dbo].[PALPACION]
(
	[PK_FK_NUMERO_TRAZABLE_VACA]	INT				NOT NULL,
	[PK_FECHA]						DATETIME		NOT NULL,
	[CONDICION_CORPORAL]			DECIMAL(2,1)	NOT NULL,
	[RESULTADO]						NVARCHAR(30)	NOT NULL,
	[CONFIRMACION]					BIT				NOT NULL,

	CONSTRAINT CK_PK_PALPACION PRIMARY KEY CLUSTERED (PK_FK_NUMERO_TRAZABLE_VACA, PK_FECHA),
	CONSTRAINT CK_PK_FK_NUMERO_TRAZABLE_VACA_PALPACION FOREIGN KEY(PK_FK_NUMERO_TRAZABLE_VACA)
		REFERENCES dbo.VACA(PK_NUMERO_TRAZABLE) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT CK_CHECK_CONDICION_CORPORAL CHECK (CONDICION_CORPORAL IN (1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5))
)
