CREATE TABLE [dbo].[PARTO]
(
	[PK_FK_NUMERO_TRAZABLE_VACA]	INT				NOT NULL,
	[PK_FK_NUMERO_TRAZABLE_TORO]	INT				NOT NULL,
	[PK_FECHA]						DATETIME		NOT NULL,
	[MUERTE_PREMATURA]				BIT				NOT NULL,
	[SEXO]							CHAR			NOT NULL,
	[CAUSA_ABORTO]					NVARCHAR(MAX)	NULL,

	CONSTRAINT CK_PK_PARTO PRIMARY KEY CLUSTERED (PK_FK_NUMERO_TRAZABLE_VACA, PK_FK_NUMERO_TRAZABLE_TORO, PK_FECHA),
	CONSTRAINT CK_PK_FK_NUMERO_TRAZABLE_VACA_PARTO FOREIGN KEY(PK_FK_NUMERO_TRAZABLE_VACA)
		REFERENCES dbo.VACA(PK_NUMERO_TRAZABLE),
	CONSTRAINT CK_PK_FK_NUMERO_TRAZABLE_TORO_PARTO FOREIGN KEY(PK_FK_NUMERO_TRAZABLE_TORO)
		REFERENCES dbo.TORO(PK_NUMERO_TRAZABLE),
	CONSTRAINT CK_CHECK_SEXO CHECK (SEXO IN ('H', 'M'))
)
