CREATE PROCEDURE [dbo].[PROC_ELIMINAR_EXAMEN]
	@numeroTrazable INT,
	@fecha	DATETIME
AS
	BEGIN
		DELETE FROM dbo.[EXAMEN_ANTROPOLOGICO]
		WHERE PK_FK_NUMERO_TRAZABLE_TORO = @numeroTrazable AND PK_FECHA = @fecha
	END
