CREATE TYPE [dbo].[TIPO_RESUMEN_VACAS] AS TABLE(
	[NUMERO_TRAZABLE]			INT				NOT NULL,
	[NOMBRE]					NVARCHAR(20)	NOT NULL,
	[EDAD_PRIMER_PARTO]			INT				NULL,
	[PARTOS]					INT				NULL,
	[EDAD_ULTIMA_CRIA]			INT				NULL,
	[FECHA_DESTETE_ULTIMA_CRIA]	DATETIME		NULL,
	[IEP_PROMEDIO]				DECIMAL(8, 2)	NULL,
	[ULTIMO_IEP]				DECIMAL(8, 2)	NULL,
	[FECHA_ULTIMA_MONTA]		DATETIME		NULL,
	[GESTACION_DIAS]			INT				NULL,
	[FECHA_PARTO]				DATETIME		NULL	
)
