CREATE TABLE [dbo].[TORO]
(
	[PK_NUMERO_TRAZABLE]	INT				NOT NULL,
	[RAZA]					NVARCHAR(30)	NULL,
	[CARACTERISTICAS]		NVARCHAR(MAX)	NOT NULL,
	[NOMBRE]				NVARCHAR(20)	NULL,

	CONSTRAINT CK_PK_NUMERO_TRAZABLE_TORO PRIMARY KEY CLUSTERED (PK_NUMERO_TRAZABLE)
)
