CREATE TRIGGER [TRIGGER_INSTEAD_OF_DELETE_VACA]
ON [dbo].[VACA]
INSTEAD OF DELETE
AS
BEGIN

	WITH V AS (SELECT * FROM [dbo].[VACA] v WHERE v.FK_NUMERO_TRAZABLE_VACA IS NOT NULL)

	UPDATE V
	SET FK_NUMERO_TRAZABLE_VACA = NULL
	WHERE FK_NUMERO_TRAZABLE_VACA IN (SELECT d.PK_NUMERO_TRAZABLE FROM deleted d)

	DELETE FROM [dbo].[VACA] WHERE PK_NUMERO_TRAZABLE IN (SELECT d.PK_NUMERO_TRAZABLE FROM deleted d)

END
