CREATE TRIGGER [TRIGGER_INSTEAD_OF_DELETE_TORO]
ON [dbo].[TORO]
INSTEAD OF DELETE
AS
BEGIN

	WITH T AS (SELECT * FROM [dbo].[VACA] v WHERE v.FK_NUMERO_TRAZABLE_TORO IS NOT NULL)

	UPDATE T
	SET FK_NUMERO_TRAZABLE_TORO = NULL
	WHERE FK_NUMERO_TRAZABLE_TORO IN (SELECT d.PK_NUMERO_TRAZABLE FROM deleted d)

	DELETE FROM [dbo].[TORO] WHERE PK_NUMERO_TRAZABLE IN (SELECT d.PK_NUMERO_TRAZABLE FROM deleted d)

END
