CREATE TABLE [dbo].[VACA]
(
	[PK_NUMERO_TRAZABLE]		INT				NOT NULL,
	[RAZA]						NVARCHAR(30)	NULL,
	[CARACTERISTICAS]			NVARCHAR(MAX)	NOT NULL,
	[NOMBRE]					NVARCHAR(20)	NULL,
	[FK_ID_MODO_PRENNES]		INT				NOT NULL,
	[FECHA_NACIMIENTO]			DATETIME		NULL,
	[FK_NUMERO_TRAZABLE_VACA]	INT				NULL,
	[FK_NUMERO_TRAZABLE_TORO]	INT				NULL,

	CONSTRAINT CK_PK_NUMERO_TRAZABLE_VACA PRIMARY KEY CLUSTERED (PK_NUMERO_TRAZABLE),
	CONSTRAINT CK_FK_NUMERO_TRAZABLE_VACA FOREIGN KEY(FK_NUMERO_TRAZABLE_VACA)
		REFERENCES dbo.VACA(PK_NUMERO_TRAZABLE),
	CONSTRAINT CK_FK_NUMERO_TRAZABLE_TORO FOREIGN KEY(FK_NUMERO_TRAZABLE_TORO)
		REFERENCES dbo.TORO(PK_NUMERO_TRAZABLE),
	CONSTRAINT CK_FK_ID_MODO_PRENNES FOREIGN KEY(FK_ID_MODO_PRENNES)
		REFERENCES dbo.MODO_PRENNES(PK_ID_MODO_PRENNES)
)
