CREATE TABLE [dbo].[VACA]
(
	[PK_NUMERO_TRAZABLE]		INT				NOT NULL,
	[FK_ID_RAZA]				INT				NOT NULL,
	[CARACTERISTICAS]			NVARCHAR(MAX)	NOT NULL,
	[NOMBRE]					NVARCHAR(20)	NULL,
	[PESO]						DECIMAL(5, 2)	NULL,
	[ACTIVA]					BIT				NOT NULL,
	[FK_ID_MODO_PRENNES]		INT				NOT NULL,
	[FECHA_NACIMIENTO]			DATETIME		NULL,
	[FK_NUMERO_TRAZABLE_VACA]	INT				NULL,
	[FK_NUMERO_TRAZABLE_TORO]	INT				NULL,
	[CAUSA_DE_BAJA]				NVARCHAR(MAX)	NULL,
	[FK_ID_DESARROLLO]			INT				NOT NULL,

	CONSTRAINT CK_PK_NUMERO_TRAZABLE_VACA PRIMARY KEY CLUSTERED (PK_NUMERO_TRAZABLE),
	CONSTRAINT CK_FK_NUMERO_TRAZABLE_VACA FOREIGN KEY(FK_NUMERO_TRAZABLE_VACA)
		REFERENCES dbo.VACA(PK_NUMERO_TRAZABLE) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT CK_FK_NUMERO_TRAZABLE_TORO FOREIGN KEY(FK_NUMERO_TRAZABLE_TORO)
		REFERENCES dbo.TORO(PK_NUMERO_TRAZABLE) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT CK_FK_ID_MODO_PRENNES FOREIGN KEY(FK_ID_MODO_PRENNES)
		REFERENCES dbo.MODO_PRENNES(PK_ID_MODO_PRENNES),
	CONSTRAINT CK_FK_VACA_RAZA FOREIGN KEY (FK_ID_RAZA)
		REFERENCES dbo.[RAZA](PK_ID_RAZA),
	CONSTRAINT CK_FK_ID_DESARROLLO FOREIGN KEY(FK_ID_DESARROLLO)
		REFERENCES dbo.DESARROLLO(PK_ID_DESARROLLO),
)
